name: Docker Image CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get version
        id: vars
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/v([0-9]+(\.[0-9]+)*)$ ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" =~ ^refs/heads/(.*)$ ]]; then
            echo "version=latest" >> $GITHUB_ENV
          else
            echo "version=unknown" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/douyin:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/douyin:latest
          file: ./Dockerfile
