name: Docker Image CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:  # 可选保留，但需处理手动触发的逻辑

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: vars
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            version="${GITHUB_REF#refs/tags/v}"
          else
            version="manual-$(date +%s)"  # 手动触发时生成唯一标识
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/douyin:${{ steps.vars.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/douyin:latest
